### ISSUE TITLE
[ERROR] Invalid code while pairing code

### ISSUE THREAD

**Issue by miruchigawa** [ArrDev10/WaBot-With-PairingCode#1]
I trying to pairing code but there has problem while pairing code

**Comment by APdev93** [comment]
What details?

**Comment by APdev93** [comment]
Issue finish, Check the documentation

**Comment by jccalbuquerque** [comment]
The eight-digit code is generated, but when entered on the cell phone it always returns that the code is invalid.
What can it be?

**Comment by APdev93** [comment]
> The eight-digit code is generated, but when entered on the cell phone it always returns that the code is invalid. What can it be?

Please send the error details
