### ISSUE TITLE
file is not in repo

### ISSUE THREAD

**Issue by joweste** [ArrDev10/WaBot-With-PairingCode#2]
Please, post the 'function.js ' file in the repo.
Regards, Luiz

**Comment by APdev93** [comment]
That file has nothing to do with pairing code

**Comment by Riders004** [comment]
How can I make it web based

**Comment by APdev93** [comment]
> How can I make it web based

You can read the official docs

**Comment by Riders004** [comment]
> > How can I make it web based
> 
> You can read the official docs

Where I can find it ?
