### ISSUE TITLE
Invalid code 

### ISSUE THREAD

**Issue by hell-ctrl** [ArrDev10/WaBot-With-PairingCode#3]
The code is being generated perfectly. But when I put it on my WhatsApp, it says that the code is invalid

**Comment by xadminx** [comment]
Same problem.

**Comment by hell-ctrl** [comment]
> Mesmo problema.

I already solve

**Comment by APdev93** [comment]
> The code is being generated perfectly. But when I put it on my WhatsApp, it says that the code is invalid

Screenshot your code

**Comment by hell-ctrl** [comment]
I already arranged

`const { default: makeWASocket, fetchLatestBaileysVersion, useMultiFileAuthState, DisconnectReason } = require("@whiskeysockets/baileys");
const pino = require("pino");
const NodeCache = require("node-cache");
const readline = require("readline");
const clc = require("cli-color");
const banner = require("../utils/banner");

const msgRetryCounterCache = new NodeCache();
const usePairingCode = process.argv.includes("--use-pairing-code")

const rl = readline.createInterface({
   input: process.stdin,
   output: process.stdout,
});

const question = (text) => new Promise((resolve) => rl.question(text, resolve));

async function connectToWhatsApp() {
   let { state, saveCreds } = await useMultiFileAuthState("./src/connection/auth");
   let { version } = await fetchLatestBaileysVersion();

   const sock = makeWASocket({
      version,
      logger: pino({level: "silent"}),
      printQRInTerminal: !usePairingCode,
      mobile: false,
      browser: ["FireFox (linux)"],
      auth: state,
      msgRetryCounterCache,
   });

   if (usePairingCode && !sock.authState.creds.registered) {
      const phoneNumber = await question(`\nDigite seu número do WhatsApp:\nEx: ${clc.bold("559885512460")}\n/> `);
      const code = await sock.requestPairingCode(phoneNumber);
      console.log(`Seu código de conexão é: ${clc.bold(code)}\n`);
      console.log(`Abra seu WhatsApp, vá em ${clc.bold("Aparelhos Conectados > Conectar um novo Aparelho > Conectar usando Número.")}`)
   }

   sock.ev.on("connection.update", (update) => {
    const { connection, lastDisconnect } = update;
    if (connection === "close") {
      const shouldReconnect = lastDisconnect.error?.output?.statusCode !== DisconnectReason.loggedOut;
      if (shouldReconnect) {
        connectToWhatsApp();
      }
    } else if (connection === "open") {
        console.log(banner.string);
        console.log(`${clc.red("➜")} ${clc.yellowBright("conectado a anny")}`);
    }
  });

  sock.ev.on("creds.update", saveCreds);
  return sock;
}

module.exports = connectToWhatsApp;`

**Comment by hell-ctrl** [comment]
I already arranged

[connection.js](https://github.com/hell-ctrl/anny-bot/blob/main/src/connection/connection.js)
