### ISSUE TITLE
Web Pair

### ISSUE THREAD

**Issue by Riders004** [ArrDev10/WaBot-With-PairingCode#4]
@APdev93 do you have Web Based Pairing Code ?

**Comment by APdev93** [comment]
> @APdev93 do you have Web Based Pairing Code ?

You can create the logic using express js

**Comment by Riders004** [comment]
I already tried but I failed if you know so can give me idea or if you have  code so can you give me that code ?

**Comment by APdev93** [comment]
> I already tried but I failed if you know so can give me idea or if you have code so can you give me that code ?

Do you have the code? If so, try sending your method here
